# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('addedOn', models.DateTimeField(auto_now_add=True)),
                ('page', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('address', models.CharField(max_length=99)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='page_images/')),
                ('imageSource', models.CharField(max_length=99)),
                ('likes', models.IntegerField(default=0)),
                ('reported', models.BooleanField()),
                ('addedOn', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('emailAddress', models.EmailField(max_length=30)),
                ('profileImage', models.ImageField(upload_to='profile_images/')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='addedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gems.User'),
        ),
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gems.Category'),
        ),
        migrations.AddField(
            model_name='comment',
            name='addedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gems.User'),
        ),
    ]
