# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-02 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='page',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
