# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gem',
            name='latitude',
            field=models.DecimalField(decimal_places=16, default=-1000, max_digits=22),
        ),
        migrations.AddField(
            model_name='gem',
            name='longitude',
            field=models.DecimalField(decimal_places=16, default=-1000, max_digits=22),
        ),
    ]
